services:
  backend:
    image: frayscc/readbox:backend-0.4.1
    container_name: readbox-backend
    environment:
      READBOX_TOKEN: ${READBOX_TOKEN}
      DATABASE_URL: sqlite:////data/readbox.db
      CORS_ORIGINS: ${CORS_ORIGINS}
    volumes:
      - ./data:/data
    networks:
      - npm
    restart: unless-stopped

  web:
    image: frayscc/readbox:web-0.4.1
    container_name: readbox-web
    depends_on:
      - backend
    networks:
      - npm
    restart: unless-stopped

networks:
  npm:
    external: true
    name: npm
